In [1]:
import tensorflow as tf

In [6]:
x = tf.random.uniform((5,4,3,2))
x = tf.convert_to_tensor(x)
for x_i in x.numpy():
  print(x_i*2)

[[[1.1013494e+00 2.4852824e-01]
  [4.7337008e-01 1.2223778e+00]
  [1.6109276e+00 9.1305590e-01]]

 [[4.2927742e-02 1.3814507e+00]
  [1.4071667e+00 1.9643683e+00]
  [5.2565479e-01 3.4738255e-01]]

 [[7.1398807e-01 1.5681460e+00]
  [2.3460555e-01 7.1252871e-01]
  [5.5441380e-02 6.8667102e-01]]

 [[1.4121532e-03 1.9570866e+00]
  [1.1182442e+00 7.6322436e-01]
  [1.3747811e-01 1.2333059e+00]]]
[[[1.435791   0.02657557]
  [1.2546918  1.384454  ]
  [1.066978   1.9347229 ]]

 [[0.3278644  1.4699931 ]
  [0.54520106 1.6130607 ]
  [0.09833813 1.4384794 ]]

 [[1.5669341  1.0195413 ]
  [1.0587673  0.31743383]
  [1.7542255  1.4841862 ]]

 [[0.04875493 0.96831465]
  [1.4469004  0.9342122 ]
  [1.0073683  1.2809184 ]]]
[[[0.20025659 1.6156328 ]
  [0.23727536 1.6991277 ]
  [1.8890979  1.4545033 ]]

 [[0.7590215  0.85148   ]
  [1.1652572  1.1552839 ]
  [0.8637364  0.95655775]]

 [[0.79097366 1.3108032 ]
  [0.10385466 1.7956102 ]
  [1.8782735  1.2524388 ]]

 [[0.17152572 0.24599886]
  [1.967763   0.482339